### PR TITLE
Fix the format of README.md

### PR DESCRIPTION
**Pull request by yiwenlu66**
Hi, hxl9654,

I am much obliged to you for your excellent work in the E programming language. I feel necessary to review this README document, but @ZeroWeight, the first author of the pull request, is more sophisticated in this field than I am, so you may ask him for further suggestions on revising this repository. He will reply you with the comments in two days. Thank you!

### CODE REVIEW

**Comment by yiwenlu66** [comment]
@ZeroWeight

**Comment by ZeroWeight** [comment]
Hi hxl9654,

We have just referred to the sheet of the reviewers, finding that  @ArcherC521 and @DavidYQY might be suitable for this revision. The invitations have been sent to them, and will they reply you with the comments in two days. Thank you!

**Comment by yiwenlu66** [comment]
Dear @Archer,

Apologies first. The mentions were automatically created and there was a mismatch due to the bug of our referral system. Although it is still in its infancy and admittedly far from robust, we firmly believe in the future of the E-language-based system, since E represents the direction of advanced productivity. @hxl9654, you may also consult @ArcherC521 for more details if you would like to follow our progress. It is a real shame that we have only done some minor work. Thank you!

**Comment by ZeroWeight** [comment]
@mcfloundinho  I have just modified the error mention manually and I have to apologies there are some minor bugs in the referral system, e.g. fail to distinguish the username with the same prefix. Apologies again.

**Comment by OctoThreadGardener** [comment]
So has this problem been solved yet? Do U need some more reviewers to review this repository?

**Pull request closed without merging**
